version: "3"
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: localhost/conspect
    container_name: conspect_app
    env_file: docker/.dockerenv
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./project:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --log-level debug --reload --workers 4
    healthcheck:
      test: [ "CMD-SHELL", "wget -O /dev/null http://localhost:8000/health_check/ || exit 1" ]
      interval: 300s
      timeout: 5s
      retries: 5
